<?php

namespace Puli;

use Puli\Discovery\Api\Discovery;
use Puli\Discovery\Binding\Initializer\ResourceBindingInitializer;
use Puli\Discovery\JsonDiscovery;
use Puli\Manager\Api\Server\ServerCollection;
use Puli\Repository\Api\ResourceRepository;
use Puli\Repository\JsonRepository;
use Puli\UrlGenerator\Api\UrlGenerator;
use Puli\UrlGenerator\DiscoveryUrlGenerator;
use RuntimeException;

/**
 * Creates Puli's core services.
 *
 * This class was auto-generated by Puli.
 *
 * IMPORTANT: Before modifying the code below, set the "factory.auto-generate"
 * configuration key to false:
 *
 *     $ puli config factory.auto-generate false
 *
 * Otherwise any modifications will be overwritten!
 */
class GeneratedPuliFactory
{
    /**
     * Creates the resource repository.
     *
     * @return ResourceRepository The created resource repository.
     */
    public function createRepository()
    {
        if (!interface_exists('Puli\Repository\Api\ResourceRepository')) {
            throw new RuntimeException('Please install puli/repository to create ResourceRepository instances.');
        }

        $repo = new JsonRepository(__DIR__.'/path-mappings.json', __DIR__.'/..', true);

        return $repo;
    }

    /**
     * Creates the resource discovery.
     *
     * @param ResourceRepository $repo The resource repository to read from.
     *
     * @return Discovery The created discovery.
     */
    public function createDiscovery(ResourceRepository $repo)
    {
        if (!interface_exists('Puli\Discovery\Api\Discovery')) {
            throw new RuntimeException('Please install puli/discovery to create Discovery instances.');
        }

        $discovery = new JsonDiscovery(__DIR__.'/bindings.json', array(
            new ResourceBindingInitializer($repo),
        ));

        return $discovery;
    }

    /**
     * Creates the URL generator.
     *
     * @param Discovery $discovery The discovery to read from.
     *
     * @return UrlGenerator The created URL generator.
     */
    public function createUrlGenerator(Discovery $discovery)
    {
        if (!interface_exists('Puli\UrlGenerator\Api\UrlGenerator')) {
            throw new RuntimeException('Please install puli/url-generator to create UrlGenerator instances.');
        }

        $generator = new DiscoveryUrlGenerator($discovery, array());

        return $generator;
    }

    /**
     * Returns the order in which the installed packages should be loaded
     * according to the override statements.
     *
     * @return string[] The sorted package names.
     */
    public function getPackageOrder()
    {
        $order = array(
            'zendframework/skeleton-application',
            'behat/behat',
            'behat/gherkin',
            'behat/mink',
            'behat/mink-browserkit-driver',
            'behat/mink-goutte-driver',
            'behat/mink-selenium2-driver',
            'behat/transliterator',
            'clue/stream-filter',
            'container-interop/container-interop',
            'doctrine/annotations',
            'doctrine/cache',
            'doctrine/collections',
            'doctrine/common',
            'doctrine/dbal',
            'doctrine/doctrine-module',
            'doctrine/doctrine-orm-module',
            'doctrine/inflector',
            'doctrine/instantiator',
            'doctrine/lexer',
            'doctrine/orm',
            'fabpot/goutte',
            'facebook/graph-sdk',
            'guzzlehttp/guzzle',
            'guzzlehttp/promises',
            'guzzlehttp/psr7',
            'happyr/linkedin-api-client',
            'instaclick/php-webdriver',
            'justinrainbow/json-schema',
            'monolog/monolog',
            'paragonie/random_compat',
            'php-http/discovery',
            'php-http/guzzle6-adapter',
            'php-http/httplug',
            'php-http/message',
            'php-http/message-factory',
            'php-http/promise',
            'psr/container',
            'psr/http-message',
            'psr/log',
            'puli/composer-plugin',
            'puli/discovery',
            'puli/repository',
            'puli/url-generator',
            'ramsey/uuid',
            'seld/jsonlint',
            'symfony/browser-kit',
            'symfony/class-loader',
            'symfony/config',
            'symfony/console',
            'symfony/css-selector',
            'symfony/debug',
            'symfony/dependency-injection',
            'symfony/dom-crawler',
            'symfony/event-dispatcher',
            'symfony/filesystem',
            'symfony/polyfill-mbstring',
            'symfony/process',
            'symfony/translation',
            'symfony/yaml',
            'webmozart/assert',
            'webmozart/expression',
            'webmozart/glob',
            'webmozart/json',
            'webmozart/path-util',
            'zendframework/zenddiagnostics',
            'zendframework/zendframework',
            'zendframework/zendxml',
            'zendframework/zftool',
        );

        return $order;
    }
}
